#! /bin/bash

function getnetwork(){
    network=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | sed "s/.*\:(.*)/\1/" -E)
    [[ -z "$network" ]] && network="none"
    echo $network
}
function getevents() {
    d=$(calcurse -n | tail -1 | sed "s/^[[:space:]]*//g")
    [[ -z "$d" ]] && d="Freee!"
    echo $d
}
function getbattery() {
    val=$(cat /sys/class/power_supply/BAT0/capacity)
    [[ $(cat /sys/class/power_supply/BAT0/status) = "Discharging" ]] || val="⟨"$val"⟩"
    echo $val
}
function get_dnd() {
    [[ $(dunstctl is-paused) == "true" ]] && echo " ﮖ |"
}
function getBTbattery() {
    level=$(dbus-send --print-reply=literal --system \
        --dest=org.bluez /org/bluez/hci0/dev_74_45_CE_1E_7D_60 \
        org.freedesktop.DBus.Properties.Get string:"org.bluez.Battery1"\
        string:"Percentage" | 
        sed -E "s/[[:space:]]{1,}/,/g" | 
        cut -d ',' -f 4)
    if [[ -z "$level" ]]; then
        echo ""
    else
        echo "|" $level " "
    fi
}
function getstatus() {
    echo  "$(get_dnd) $(getevents) │ $(date +%A\ %b\ %d\ \│\ %R) │ $(getbattery) $(getBTbattery)"
}
xsetroot -name "$(getstatus)"


